travis:
  secure:
    BINSTAR_TOKEN: LHqXTNVGlhKbZZlrZckCYpHLKCJaE8q3DvBrBa6tnq5GlpKJVBNa0E/yBNivZ81McoKkPaSUj2FyoGCeeDIgxHA0P3cCAnbVHdtE27gnXko4J/WKX1Qffl4eVctXvirlj40XtcDpAxYaBFXGCoq3YmmEk8y+L2nVJFs3rdM/WeyNo+80rrosY09Fe1ei5rlJCa8HKEYiMA+4uqiMt4p8TMIG04bf7RBiL9KeNuv6UvNO7eTbqRA8L7VRg7UbvXVLu8Bypl5jkSTVz7Gml2r0MmOQCMqk6uuUMJTFz6oqhov0Wqk8wpxXQQYIeLFzxqt3LBNoflpgFfYMST9SK6mAezQXZg7Ku+7Ist/RotMQ0KDl8pGm8vElw03QSA4dGolhl2AuOvY2hlmm5caAH3UjREIGYbMktexZR8rQ6yhwhorf6w+97nTk2WR6YfqLRabhXikR0w8NxiBJniuiRI23cCD05FITRIKU+FH3YogIC5ohzaKpmMSs/I/dcvLiZEbUJKZlbFK9oGesriQcnOO2ZBu0F8WXYdOYXuRiiegFHsUfu5ex1InOQxd0EzcSJsZIfcpI6yDlPgv7GtezASnaLC4NZP9kFdEwuuUCsluyyqmp0A0jMSGztIjupoNV1li8hkthz0iz4+aYqeuBwaW/X4tpYSuX8SkWkFoXEB9ejrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
